/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /health` — public heartbeat endpoint.
         * @description Returns a JSON snapshot of system vitals. No authentication required.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns all created users (admins and regular users).
         *     API keys are not included — only name, role, and creation timestamp.
         */
        get: operations["list_users"];
        put?: never;
        /**
         * Creates a new user with the `User` role.
         *     The API key is returned **only in this response** and is not stored afterward.
         *     Only admins may call this endpoint.
         */
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/auth/users/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletes a user and all of their domain permissions.
         *     The user's API key becomes invalid immediately — in-flight requests with the old key then get `401`.
         */
        delete: operations["delete_user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/auth/users/{name}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sets or overwrites a user's access permission on a domain.
         *     `access` must be `"read"`, `"write"`, or `"ddl"` — each level includes the
         *     lower ones. For `kv` the domain must exist; `json`/`rel` only check the name.
         */
        post: operations["set_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/auth/users/{name}/permissions/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revokes a user's access permission on a specific domain.
         *     `?store_type=json`/`rel` revokes a JSON/rel domain permission (default: kv).
         *     After this call, the user's requests to this domain get `403 Forbidden`.
         */
        delete: operations["remove_permission"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/auth/users/{name}/rotate-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generates a new API key for the user and immediately invalidates the old one.
         *     The new key is returned **only in this response**.
         *     Use this after key leaks or for regular key rotation.
         */
        post: operations["rotate_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns all active domains with their names and creation timestamps. */
        get: operations["list_domains"];
        put?: never;
        /**
         * Creates a new logical domain (isolated KV namespace).
         *     Domain names must be unique, max 50 chars, and match `[a-zA-Z0-9_-]`.
         */
        post: operations["create_domain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/domains/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns metadata for a single domain by name. Returns 404 if it does not exist. */
        get: operations["get_domain"];
        put?: never;
        post?: never;
        /**
         * Schedules a domain and all its data for deletion.
         *     The domain becomes immediately inaccessible; the actual purge runs in the background.
         */
        delete: operations["delete_domain"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns all active JSON domains. */
        get: operations["json_list_domains_1"];
        put?: never;
        /** Creates a new JSON domain (isolated document namespace, separate from KV domains). */
        post: operations["json_create_domain_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/domains/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns metadata for a single JSON domain, including its document count.
         *     Domains in `deleting` state answer with 410 Gone.
         */
        get: operations["json_get_domain_1"];
        put?: never;
        post?: never;
        /** Marks a JSON domain as deleting. Documents become inaccessible immediately. */
        delete: operations["json_delete_domain_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Imports documents from an NDJSON body in atomic batches. */
        post: operations["bulk_load"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists documents of a domain without filters (natural key order). */
        get: operations["list_documents"];
        put?: never;
        /** Stores a document under a system-generated UUIDv4 key (create-only). */
        post: operations["create_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/documents/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts all documents of a domain (key scan only). */
        get: operations["count_documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/documents/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reads a document; `_key`/`_version` are top-level fields and an opaque
         *     `ETag` is exposed for use with `If-Match` (json/011).
         */
        get: operations["get_document"];
        /**
         * Upserts a document. With an `If-Match: "<etag>"` header the write is a
         *     conditional update that fails with 409 on a version mismatch.
         */
        put: operations["put_document"];
        post?: never;
        /**
         * Deletes a document and its index entries. Supports conditional delete via
         *     `If-Match: "<etag>"`.
         */
        delete: operations["delete_document"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Streams all documents of a domain as NDJSON without full buffering. */
        get: operations["export_documents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all index definitions of a domain. */
        get: operations["list_indexes"];
        put?: never;
        /**
         * Creates an index definition. Existing documents are NOT back-indexed —
         *     trigger a re-index for that.
         */
        post: operations["create_index"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/indexes/{field}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes an index definition. */
        delete: operations["delete_index"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a background re-index of the domain (all indexes, or one field). */
        post: operations["trigger_reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/reindex/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns the status of a re-index task. Tasks are domain-scoped: a task id
         *     of another domain answers 404 (tenant isolation).
         */
        get: operations["reindex_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/json/{domain}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Searches documents via indexed fields. Filters: `"field": value` for
         *     equality or `"field": {"$gt": …}` for ranges; multiple fields are ANDed.
         */
        post: operations["search_documents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/kv/{domain}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all keys in the domain, optionally filtered by a prefix. Returns an empty array if no keys match. */
        get: operations["scan_keys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/kv/{domain}/keys/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the raw byte value for a key. Returns 204 for a key in the null state and 404 if the key does not exist or has expired. */
        get: operations["get_key"];
        /**
         * Inserts or updates a value for the given key (upsert semantics).
         *     The optional `ttl` query parameter sets an expiry in seconds; omitting it stores the key indefinitely.
         */
        put: operations["put_key"];
        post?: never;
        /** Permanently removes a key from the domain. The operation is idempotent; deleting a non-existent key still returns 204. */
        delete: operations["delete_key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/kv/{domain}/keys/{key}/null": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Sets the key to an explicit null value (upsert): the key stays registered and appears in scans,
         *     but carries no data — GET answers 204. A write like any other; it resets a previously set TTL.
         */
        patch: operations["set_null"];
        trace?: never;
    };
    "/store-api/kv/{domain}/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Opens a Server-Sent Events stream that delivers real-time change events (`set` / `delete`) for keys matching the optional prefix.
         *     The connection stays open until the client disconnects; a keep-alive ping is sent automatically.
         */
        get: operations["watch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /metrics` — system + all domain metrics. Admin only. */
        get: operations["get_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/metrics/domains/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /metrics/domains/{name}` — metrics for one domain. Admin or domain user. */
        get: operations["get_domain_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/rel/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns all active relational domains. */
        get: operations["rel_list_domains_2"];
        put?: never;
        /**
         * Creates a new relational domain (isolated table/view namespace, separate
         *     from KV and JSON domains).
         */
        post: operations["rel_create_domain_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/rel/domains/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns metadata for a single relational domain. A domain in `deleting`
         *     state answers 410 Gone (rel/013 finishes the physical purge).
         */
        get: operations["rel_get_domain_2"];
        put?: never;
        post?: never;
        /**
         * Marks a relational domain as deleting. Its tables/views become
         *     inaccessible immediately; physical cleanup follows in rel/013.
         */
        delete: operations["rel_delete_domain_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/rel/{domain}/sql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Executes exactly one LuraSQL statement against `domain` and returns its
         *     typed result. `expand` resolves REFERENCES columns of a SELECT into
         *     embedded objects (or `"*"` for every REFERENCES column).
         */
        post: operations["execute_sql"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/rel/{domain}/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the tables of a domain (views are listed separately, `GET …/views`). */
        get: operations["list_tables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/rel/{domain}/tables/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a table's schema (columns, indexes) plus HATEOAS links. A view
         *     name answers 404 here — use `GET …/views` for views.
         */
        get: operations["get_table"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/rel/{domain}/tables/{table}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists rows of `table`. Every query parameter other than `expand`/`limit`/
         *     `offset` is an equality filter on the like-named column (`?col=value`,
         *     AND-combined); parse errors and unknown filter columns answer 400. This
         *     compiles onto the same bound `*`-SELECT plan `/sql` would use.
         */
        get: operations["browse_rows"];
        put?: never;
        /**
         * Inserts one row from a JSON object body (`{column: value, …}`). An omitted
         *     AUTOINCREMENT primary key is assigned the next sequence value (rel/005
         *     §9); this compiles onto the exact same bound INSERT plan `/sql` would use.
         */
        post: operations["insert_row"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/rel/{domain}/tables/{table}/rows/{pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetches a single row by primary key — the same PK-point SELECT plan
         *     `/sql`'s `WHERE pk = ?` would use.
         */
        get: operations["get_row"];
        /**
         * Partially updates a row by primary key: only the columns named in the
         *     body are set, everything else stays unchanged (spec §5). Not an upsert —
         *     a PK the table doesn't have answers 404, never a create.
         */
        put: operations["update_row"];
        post?: never;
        /**
         * Deletes a row by primary key. Hanging REFERENCES from other tables are
         *     not blocked by this (rel/005 §11) — they resolve to `null` afterwards.
         */
        delete: operations["delete_row"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store-api/rel/{domain}/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the views of a domain, including their raw (unmodified) SQL text. */
        get: operations["list_views"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /version` — version handshake. Requires any valid API key. */
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BulkErrorEntry: {
            error: string;
            /** @description Document key or "line N" for parse errors. */
            key: string;
        };
        BulkLoadResponse: {
            errors: components["schemas"]["BulkErrorEntry"][];
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            imported: number;
        };
        ColumnInfo: {
            autoincrement: boolean;
            default?: Record<string, never>;
            name: string;
            nullable: boolean;
            primary_key: boolean;
            references?: string | null;
            type: string;
            unique: boolean;
        };
        CountResponse: {
            /** Format: int64 */
            count: number;
        };
        CreateDomainRequest: {
            /** @description User-visible domain name (max 50 chars, [a-zA-Z0-9_-]). */
            name: string;
        };
        CreateIndexRequest: {
            /** @description JSON field path, dot notation for nested fields (e.g. "address.city"). */
            field: string;
            /** @description Value type: "string" | "number" | "boolean". */
            type: string;
        };
        CreateJsonDomainRequest: {
            /** @description User-visible domain name (max 50 chars, [a-zA-Z0-9_-]). */
            name: string;
        };
        CreateRelDomainRequest: {
            /** @description Domain name (max 50 chars, `[a-zA-Z0-9_-]`; `"domains"` is reserved). */
            name: string;
        };
        CreateUserRequest: {
            /** @description Username (1-50 chars, only [a-zA-Z0-9_-]). */
            name: string;
        };
        CreateUserResponse: {
            /** @description API key (visible only once — cannot be retrieved afterward). */
            api_key: string;
            name: string;
            role: string;
        };
        DocumentListResponse: {
            /** @description Loaded documents incl. `_key`/`_version` (empty when keys_only). */
            documents: Record<string, never>[];
            /** @description Document keys of the page. */
            keys: string[];
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        DomainResponse: {
            /**
             * Format: int64
             * @description Creation timestamp (Unix seconds).
             */
            created_at: number;
            /** @description User-visible domain name. */
            name: string;
        };
        IndexInfo: {
            column: string;
            name: string;
            unique: boolean;
        };
        IndexResponse: {
            /** Format: int64 */
            created_at: number;
            field: string;
            type: string;
        };
        JsonDomainResponse: {
            /**
             * Format: int64
             * @description Creation timestamp (Unix seconds).
             */
            created_at: number;
            /**
             * Format: int64
             * @description Number of documents — only set on the detail endpoint.
             */
            document_count?: number | null;
            name: string;
            /** @description Lifecycle state: "active" or "deleting" (background purge running). */
            state: string;
        };
        ListParams: {
            keys_only?: boolean | null;
            /** Format: int32 */
            limit?: number | null;
            /** Format: int32 */
            offset?: number | null;
        };
        ReindexAcceptedResponse: {
            task_id: string;
        };
        ReindexRequest: {
            /** @description Optional: re-index only this field's index. Omit for all indexes. */
            field?: string | null;
        };
        RelDomainResponse: {
            /**
             * Format: int64
             * @description Creation timestamp (Unix seconds).
             */
            created_at: number;
            name: string;
            /**
             * @description Lifecycle state: "active" or "deleting" (background purge running, rel/013).
             *     Always present — so rel/013's later `list_domains` visibility change
             *     (surfacing `Deleting` domains too) needs no REST-contract change.
             */
            state: string;
        };
        RotateKeyResponse: {
            /** @description New API key (visible only once — cannot be retrieved afterward). */
            api_key: string;
            name: string;
        };
        RowsResponse: {
            /** Format: int64 */
            limit: number;
            limit_applied: boolean;
            /** Format: int64 */
            offset: number;
            row_count: number;
            /**
             * @description One JSON object per row (catalog column order in principle; `serde_json`'s
             *     default map is unordered/alphabetical here, see rel_browse.rs module docs),
             *     with an optional `_expanded` block (spec §6).
             */
            rows: Record<string, never>[];
        };
        SearchRequest: {
            /** @description Field → value (Eq) or `{"$gt": …}` / `$gte` / `$lt` / `$lte` / `$eq`. */
            filter?: Record<string, never>;
            /** Format: int32 */
            limit?: number | null;
            /** Format: int32 */
            offset?: number | null;
        };
        SearchResponse: {
            /** @description Matching documents incl. `_key`/`_version` metadata. */
            documents: Record<string, never>[];
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        SetPermissionRequest: {
            /** @description Access level: `"read"`, `"write"` or `"ddl"` (spec rel/011). */
            access: string;
            /** @description Domain name. */
            domain: string;
            /** @description Store type of the domain: `"kv"` (default), `"json"` (spec json/012) or `"rel"` (spec rel/011). */
            store_type?: string | null;
        };
        SqlRequest: {
            /**
             * @description REFERENCES columns to resolve into embedded objects, or `["*"]` for
             *     all of them (§5). Only valid for SELECT; non-empty on DML/DDL → 400.
             */
            expand?: string[];
            /**
             * @description Positional parameters (JSON array), bound to the `?` placeholders
             *     (rel/004/005). Omitted ⇒ empty array.
             */
            params?: Record<string, never>[];
            /** @description Exactly one LuraSQL statement (more → 400 `MultipleStatements`, rel/004). */
            sql: string;
        };
        TableDetail: {
            _links: components["schemas"]["TableLinks"];
            columns: components["schemas"]["ColumnInfo"][];
            /** Format: int64 */
            created_at: number;
            indexes: components["schemas"]["IndexInfo"][];
            name: string;
        };
        TableLinks: {
            rows: string;
            self: string;
        };
        TableSummary: {
            _links: components["schemas"]["TableLinks"];
            name: string;
        };
        UserListItem: {
            /** Format: int64 */
            created_at: number;
            name: string;
            role: string;
        };
        VersionResponse: {
            /** @description API contract version — identical to the contract's `info.version`. */
            api_version: string;
            /** @description Server version (CARGO_PKG_VERSION). */
            server_version: string;
        };
        ViewSummary: {
            /** Format: int64 */
            created_at: number;
            name: string;
            sql: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all users (without API keys) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItem"][];
                };
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created. API key is shown once in the response. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserResponse"];
                };
            };
            /** @description Invalid name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User and all permissions deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_permission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPermissionRequest"];
            };
        };
        responses: {
            /** @description Permission set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid access or domain value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User or domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_permission: {
        parameters: {
            query?: {
                /** @description 'kv' (default), 'json' or 'rel' */
                store_type?: string;
            };
            header?: never;
            path: {
                /** @description Username */
                name: string;
                /** @description Domain name */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Permission revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Permission not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotate_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New API key generated (visible once) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateKeyResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_domains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active domains */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"][];
                };
            };
        };
    };
    create_domain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDomainRequest"];
            };
        };
        responses: {
            /** @description Domain created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
            /** @description Invalid domain name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_domain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Domain name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_domain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Domain name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion accepted — background purge started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    json_list_domains_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active JSON domains */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonDomainResponse"][];
                };
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    json_create_domain_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJsonDomainRequest"];
            };
        };
        responses: {
            /** @description JSON domain created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonDomainResponse"];
                };
            };
            /** @description Invalid domain name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    json_get_domain_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonDomainResponse"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted (background purge running) */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    json_delete_domain_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion accepted — background purge follows */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bulk_load: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
            };
            cookie?: never;
        };
        /** @description NDJSON — one document per line, optional _key field */
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            /** @description Import summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkLoadResponse"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_documents: {
        parameters: {
            query?: {
                /** @description Page size (default 50, max 1000) */
                limit?: number;
                /** @description Documents to skip */
                offset?: number;
                /** @description Return only keys, no content */
                keys_only?: boolean;
            };
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated document list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Document created with generated UUIDv4 key */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    count_documents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountResponse"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
                /** @description Document key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document content with _key/_version metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document or domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
                /** @description Document key */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Document updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid key or If-Match header */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain not found, or If-Match on missing document */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version conflict (If-Match mismatch) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
                /** @description Document key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document or domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version conflict (If-Match mismatch) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_documents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream of all documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": unknown;
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_indexes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index definitions of the domain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"][];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_index: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIndexRequest"];
            };
        };
        responses: {
            /** @description Index definition created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description Invalid field or type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Index already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_index: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
                /** @description Indexed field path */
                field: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index definition removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Index or domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_reindex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
            };
            cookie?: never;
        };
        /** @description Optional field restriction */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReindexRequest"];
            };
        };
        responses: {
            /** @description Re-index started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexAcceptedResponse"];
                };
            };
            /** @description Malformed request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Re-index already running for this domain */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reindex_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
                /** @description Re-index task id */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current re-index status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown task id for this domain */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_documents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JSON domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Matching documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Invalid filter or unindexed field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description JSON engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scan_keys: {
        parameters: {
            query?: {
                /** @description Key prefix filter */
                prefix?: string;
            };
            header?: never;
            path: {
                /** @description Domain name */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of matching keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Domain name */
                domain: string;
                /** @description Key (valid UTF-8, max 256 bytes) */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Value (raw bytes; an empty value yields an empty body) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Key exists in the explicit null state (set via PATCH …/null) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Key or domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_key: {
        parameters: {
            query?: {
                /** @description TTL in seconds (optional) */
                ttl?: number;
            };
            header?: never;
            path: {
                /** @description Domain name */
                domain: string;
                /** @description Key (valid UTF-8, max 256 bytes) */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/plain": string;
            };
        };
        responses: {
            /** @description Key upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Domain name */
                domain: string;
                /** @description Key (valid UTF-8, max 256 bytes) */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_null: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Domain name */
                domain: string;
                /** @description Key (valid UTF-8, max 256 bytes) */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key set to the null value state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    watch: {
        parameters: {
            query?: {
                /** @description Key prefix filter */
                prefix?: string;
            };
            header?: never;
            path: {
                /** @description Domain name */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of key change events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_domain_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Domain name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain metrics snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain not found or no metrics yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rel_list_domains_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active relational domains */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelDomainResponse"][];
                };
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rel_create_domain_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRelDomainRequest"];
            };
        };
        responses: {
            /** @description Relational domain created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelDomainResponse"];
                };
            };
            /** @description Invalid domain name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rel_get_domain_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relational domain name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelDomainResponse"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted (background purge running) */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rel_delete_domain_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relational domain name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion accepted — background purge follows (rel/013) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is already being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    execute_sql: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relational domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SqlRequest"];
            };
        };
        responses: {
            /** @description Statement result. Shape depends on the statement class — DDL: {"ok":true}; INSERT/UPDATE/DELETE: {"affected","last_pk"}; SELECT: {"columns":[{"name","type"}],"rows":[[...]],"row_count","limit_applied","expanded"?}. `rows` are arrays (not objects) so same-named JOIN columns don't collide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Syntax, type, parameter-count, or expand error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access level too low for this statement (rel/011) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain, table, column, or index not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict — duplicate key, unique violation, name collision, … */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Response exceeds max_response_bytes */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-domain request budget exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_tables: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relational domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tables of the domain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableSummary"][];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-domain request budget exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_table: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relational domain */
                domain: string;
                /** @description Table name */
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Table schema detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableDetail"];
                };
            };
            /** @description Domain or table not found (a view is not a table) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-domain request budget exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    browse_rows: {
        parameters: {
            query?: {
                /** @description Comma-separated REFERENCES columns to resolve, or "*" for all */
                expand?: string;
                /** @description Max rows to return (falls back to the configured default, capped at the configured max) */
                limit?: number;
                /** @description Rows to skip */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Relational domain */
                domain: string;
                /** @description Table name */
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching rows as objects, with row_count/limit/offset/limit_applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsResponse"];
                };
            };
            /** @description Unknown filter column, or a filter/limit/offset parse/type error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain or table not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Response exceeds max_response_bytes */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-domain request budget exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    insert_row: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relational domain */
                domain: string;
                /** @description Table name */
                table: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Row inserted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description NOT NULL/type/schema violation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain, table, or referenced body column not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PK collision, unique violation, or missing REFERENCES target */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-domain request budget exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_row: {
        parameters: {
            query?: {
                /** @description Comma-separated REFERENCES columns to resolve, or "*" */
                expand?: string;
            };
            header?: never;
            path: {
                /** @description Relational domain */
                domain: string;
                /** @description Table name */
                table: string;
                /** @description Primary key value */
                pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The row as an object, with an optional _expanded block */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description PK parse/type error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain, table, or row not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Response exceeds max_response_bytes */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-domain request budget exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_row: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relational domain */
                domain: string;
                /** @description Table name */
                table: string;
                /** @description Primary key value */
                pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Row updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description NOT NULL/type/schema violation, or body primary key != path primary key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain, table, column, or row not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unique violation, or missing REFERENCES target */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-domain request budget exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_row: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relational domain */
                domain: string;
                /** @description Table name */
                table: string;
                /** @description Primary key value */
                pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Row deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description PK parse/type error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain, table, or row not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-domain request budget exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_views: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Relational domain */
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Views of the domain, incl. raw SQL text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewSummary"][];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Domain is being deleted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Per-domain request budget exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Relational engine disabled */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server and API contract version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Unauthorized — a valid API key is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
