const IDENTIFIER_PATTERN = /^[a-z_][a-z0-9_]{0,49}$/

// LuraSQL reserviert jedes Schlüsselwort und jeden Typnamen/Alias als Identifier (api/LURASQL.md, Abschnitt "Identifier").
const RESERVED_WORDS = new Set([
  'create',
  'table',
  'alter',
  'drop',
  'add',
  'column',
  'rename',
  'to',
  'index',
  'unique',
  'on',
  'view',
  'as',
  'insert',
  'into',
  'values',
  'update',
  'set',
  'delete',
  'from',
  'select',
  'left',
  'outer',
  'join',
  'where',
  'order',
  'by',
  'asc',
  'desc',
  'limit',
  'offset',
  'and',
  'or',
  'not',
  'in',
  'like',
  'is',
  'null',
  'primary',
  'key',
  'autoincrement',
  'default',
  'references',
  'count',
  'current_timestamp',
  'true',
  'false',
  'integer',
  'int',
  'bigint',
  'smallint',
  'real',
  'float',
  'double',
  'text',
  'varchar',
  'char',
  'boolean',
  'bool',
  'timestamp',
  'datetime',
  'kvref',
  'jsonref',
])

/** Identifier-Regel (api/LURASQL.md): `[a-z_][a-z0-9_]{0,49}`, alle Keywords/Typnamen reserviert. `undefined` = gültig. */
export function identifierError(value: string): string | undefined {
  if (value === '') return 'name is required'
  if (!IDENTIFIER_PATTERN.test(value)) return 'must be lowercase, start with a letter or _, only [a-z0-9_], max 50 chars'
  if (RESERVED_WORDS.has(value)) return `"${value}" is a reserved word`
  return undefined
}
